// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlkfyeavtjyjgzgukwhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indsa2Z5ZWF2dGp5amd6Z3Vrd2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MTkwOTUsImV4cCI6MjA3NDM5NTA5NX0.OP5dse8qfADuqXe3LuB5WRDvxO3JA-RM-BrgXp1aeY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});